// Code generated by ent, DO NOT EDIT.

package migrate

import (
	"entgo.io/ent/dialect/sql/schema"
	"entgo.io/ent/schema/field"
)

var (
	// AgentsColumns holds the columns for the "agents" table.
	AgentsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeString, Unique: true},
		{Name: "tenant_id", Type: field.TypeString, Default: "local"},
		{Name: "type", Type: field.TypeEnum, Enums: []string{"tmux", "process"}},
		{Name: "config", Type: field.TypeJSON},
		{Name: "channel_id", Type: field.TypeString},
		{Name: "status", Type: field.TypeEnum, Enums: []string{"online", "offline"}, Default: "offline"},
	}
	// AgentsTable holds the schema information for the "agents" table.
	AgentsTable = &schema.Table{
		Name:       "agents",
		Columns:    AgentsColumns,
		PrimaryKey: []*schema.Column{AgentsColumns[0]},
		Indexes: []*schema.Index{
			{
				Name:    "agent_channel_id",
				Unique:  true,
				Columns: []*schema.Column{AgentsColumns[4]},
			},
			{
				Name:    "agent_tenant_id",
				Unique:  false,
				Columns: []*schema.Column{AgentsColumns[1]},
			},
		},
	}
	// EventsColumns holds the columns for the "events" table.
	EventsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeString, Unique: true},
		{Name: "tenant_id", Type: field.TypeString, Default: "local"},
		{Name: "agent_id", Type: field.TypeString},
		{Name: "channel_id", Type: field.TypeString},
		{Name: "type", Type: field.TypeEnum, Enums: []string{"human_message", "agent_message", "interrupt", "system"}},
		{Name: "role", Type: field.TypeEnum, Enums: []string{"human", "agent", "system"}},
		{Name: "timestamp", Type: field.TypeTime},
		{Name: "payload", Type: field.TypeJSON},
		{Name: "status", Type: field.TypeEnum, Enums: []string{"new", "delivered", "failed"}, Default: "new"},
		{Name: "source_agent_id", Type: field.TypeString, Nullable: true, Default: ""},
	}
	// EventsTable holds the schema information for the "events" table.
	EventsTable = &schema.Table{
		Name:       "events",
		Columns:    EventsColumns,
		PrimaryKey: []*schema.Column{EventsColumns[0]},
		Indexes: []*schema.Index{
			{
				Name:    "event_agent_id_timestamp",
				Unique:  false,
				Columns: []*schema.Column{EventsColumns[2], EventsColumns[6]},
			},
			{
				Name:    "event_channel_id",
				Unique:  false,
				Columns: []*schema.Column{EventsColumns[3]},
			},
			{
				Name:    "event_tenant_id",
				Unique:  false,
				Columns: []*schema.Column{EventsColumns[1]},
			},
			{
				Name:    "event_status",
				Unique:  false,
				Columns: []*schema.Column{EventsColumns[8]},
			},
		},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		AgentsTable,
		EventsTable,
	}
)

func init() {
}
