// Code generated by ent, DO NOT EDIT.

package ent

import (
	"github.com/plexusone/agentcomms/ent/agent"
	"github.com/plexusone/agentcomms/ent/event"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/entql"
	"entgo.io/ent/schema/field"
)

// schemaGraph holds a representation of ent/schema at runtime.
var schemaGraph = func() *sqlgraph.Schema {
	graph := &sqlgraph.Schema{Nodes: make([]*sqlgraph.Node, 2)}
	graph.Nodes[0] = &sqlgraph.Node{
		NodeSpec: sqlgraph.NodeSpec{
			Table:   agent.Table,
			Columns: agent.Columns,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeString,
				Column: agent.FieldID,
			},
		},
		Type: "Agent",
		Fields: map[string]*sqlgraph.FieldSpec{
			agent.FieldTenantID:  {Type: field.TypeString, Column: agent.FieldTenantID},
			agent.FieldType:      {Type: field.TypeEnum, Column: agent.FieldType},
			agent.FieldConfig:    {Type: field.TypeJSON, Column: agent.FieldConfig},
			agent.FieldChannelID: {Type: field.TypeString, Column: agent.FieldChannelID},
			agent.FieldStatus:    {Type: field.TypeEnum, Column: agent.FieldStatus},
		},
	}
	graph.Nodes[1] = &sqlgraph.Node{
		NodeSpec: sqlgraph.NodeSpec{
			Table:   event.Table,
			Columns: event.Columns,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeString,
				Column: event.FieldID,
			},
		},
		Type: "Event",
		Fields: map[string]*sqlgraph.FieldSpec{
			event.FieldTenantID:      {Type: field.TypeString, Column: event.FieldTenantID},
			event.FieldAgentID:       {Type: field.TypeString, Column: event.FieldAgentID},
			event.FieldChannelID:     {Type: field.TypeString, Column: event.FieldChannelID},
			event.FieldType:          {Type: field.TypeEnum, Column: event.FieldType},
			event.FieldRole:          {Type: field.TypeEnum, Column: event.FieldRole},
			event.FieldTimestamp:     {Type: field.TypeTime, Column: event.FieldTimestamp},
			event.FieldPayload:       {Type: field.TypeJSON, Column: event.FieldPayload},
			event.FieldStatus:        {Type: field.TypeEnum, Column: event.FieldStatus},
			event.FieldSourceAgentID: {Type: field.TypeString, Column: event.FieldSourceAgentID},
		},
	}
	return graph
}()

// predicateAdder wraps the addPredicate method.
// All update, update-one and query builders implement this interface.
type predicateAdder interface {
	addPredicate(func(s *sql.Selector))
}

// addPredicate implements the predicateAdder interface.
func (_q *AgentQuery) addPredicate(pred func(s *sql.Selector)) {
	_q.predicates = append(_q.predicates, pred)
}

// Filter returns a Filter implementation to apply filters on the AgentQuery builder.
func (_q *AgentQuery) Filter() *AgentFilter {
	return &AgentFilter{config: _q.config, predicateAdder: _q}
}

// addPredicate implements the predicateAdder interface.
func (m *AgentMutation) addPredicate(pred func(s *sql.Selector)) {
	m.predicates = append(m.predicates, pred)
}

// Filter returns an entql.Where implementation to apply filters on the AgentMutation builder.
func (m *AgentMutation) Filter() *AgentFilter {
	return &AgentFilter{config: m.config, predicateAdder: m}
}

// AgentFilter provides a generic filtering capability at runtime for AgentQuery.
type AgentFilter struct {
	predicateAdder
	config
}

// Where applies the entql predicate on the query filter.
func (f *AgentFilter) Where(p entql.P) {
	f.addPredicate(func(s *sql.Selector) {
		if err := schemaGraph.EvalP(schemaGraph.Nodes[0].Type, p, s); err != nil {
			s.AddError(err)
		}
	})
}

// WhereID applies the entql string predicate on the id field.
func (f *AgentFilter) WhereID(p entql.StringP) {
	f.Where(p.Field(agent.FieldID))
}

// WhereTenantID applies the entql string predicate on the tenant_id field.
func (f *AgentFilter) WhereTenantID(p entql.StringP) {
	f.Where(p.Field(agent.FieldTenantID))
}

// WhereType applies the entql string predicate on the type field.
func (f *AgentFilter) WhereType(p entql.StringP) {
	f.Where(p.Field(agent.FieldType))
}

// WhereConfig applies the entql json.RawMessage predicate on the config field.
func (f *AgentFilter) WhereConfig(p entql.BytesP) {
	f.Where(p.Field(agent.FieldConfig))
}

// WhereChannelID applies the entql string predicate on the channel_id field.
func (f *AgentFilter) WhereChannelID(p entql.StringP) {
	f.Where(p.Field(agent.FieldChannelID))
}

// WhereStatus applies the entql string predicate on the status field.
func (f *AgentFilter) WhereStatus(p entql.StringP) {
	f.Where(p.Field(agent.FieldStatus))
}

// addPredicate implements the predicateAdder interface.
func (_q *EventQuery) addPredicate(pred func(s *sql.Selector)) {
	_q.predicates = append(_q.predicates, pred)
}

// Filter returns a Filter implementation to apply filters on the EventQuery builder.
func (_q *EventQuery) Filter() *EventFilter {
	return &EventFilter{config: _q.config, predicateAdder: _q}
}

// addPredicate implements the predicateAdder interface.
func (m *EventMutation) addPredicate(pred func(s *sql.Selector)) {
	m.predicates = append(m.predicates, pred)
}

// Filter returns an entql.Where implementation to apply filters on the EventMutation builder.
func (m *EventMutation) Filter() *EventFilter {
	return &EventFilter{config: m.config, predicateAdder: m}
}

// EventFilter provides a generic filtering capability at runtime for EventQuery.
type EventFilter struct {
	predicateAdder
	config
}

// Where applies the entql predicate on the query filter.
func (f *EventFilter) Where(p entql.P) {
	f.addPredicate(func(s *sql.Selector) {
		if err := schemaGraph.EvalP(schemaGraph.Nodes[1].Type, p, s); err != nil {
			s.AddError(err)
		}
	})
}

// WhereID applies the entql string predicate on the id field.
func (f *EventFilter) WhereID(p entql.StringP) {
	f.Where(p.Field(event.FieldID))
}

// WhereTenantID applies the entql string predicate on the tenant_id field.
func (f *EventFilter) WhereTenantID(p entql.StringP) {
	f.Where(p.Field(event.FieldTenantID))
}

// WhereAgentID applies the entql string predicate on the agent_id field.
func (f *EventFilter) WhereAgentID(p entql.StringP) {
	f.Where(p.Field(event.FieldAgentID))
}

// WhereChannelID applies the entql string predicate on the channel_id field.
func (f *EventFilter) WhereChannelID(p entql.StringP) {
	f.Where(p.Field(event.FieldChannelID))
}

// WhereType applies the entql string predicate on the type field.
func (f *EventFilter) WhereType(p entql.StringP) {
	f.Where(p.Field(event.FieldType))
}

// WhereRole applies the entql string predicate on the role field.
func (f *EventFilter) WhereRole(p entql.StringP) {
	f.Where(p.Field(event.FieldRole))
}

// WhereTimestamp applies the entql time.Time predicate on the timestamp field.
func (f *EventFilter) WhereTimestamp(p entql.TimeP) {
	f.Where(p.Field(event.FieldTimestamp))
}

// WherePayload applies the entql json.RawMessage predicate on the payload field.
func (f *EventFilter) WherePayload(p entql.BytesP) {
	f.Where(p.Field(event.FieldPayload))
}

// WhereStatus applies the entql string predicate on the status field.
func (f *EventFilter) WhereStatus(p entql.StringP) {
	f.Where(p.Field(event.FieldStatus))
}

// WhereSourceAgentID applies the entql string predicate on the source_agent_id field.
func (f *EventFilter) WhereSourceAgentID(p entql.StringP) {
	f.Where(p.Field(event.FieldSourceAgentID))
}
