// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/plexusone/agentcomms/ent/event"
	"github.com/plexusone/agentcomms/ent/predicate"
)

// EventUpdate is the builder for updating Event entities.
type EventUpdate struct {
	config
	hooks    []Hook
	mutation *EventMutation
}

// Where appends a list predicates to the EventUpdate builder.
func (_u *EventUpdate) Where(ps ...predicate.Event) *EventUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetTenantID sets the "tenant_id" field.
func (_u *EventUpdate) SetTenantID(v string) *EventUpdate {
	_u.mutation.SetTenantID(v)
	return _u
}

// SetNillableTenantID sets the "tenant_id" field if the given value is not nil.
func (_u *EventUpdate) SetNillableTenantID(v *string) *EventUpdate {
	if v != nil {
		_u.SetTenantID(*v)
	}
	return _u
}

// SetAgentID sets the "agent_id" field.
func (_u *EventUpdate) SetAgentID(v string) *EventUpdate {
	_u.mutation.SetAgentID(v)
	return _u
}

// SetNillableAgentID sets the "agent_id" field if the given value is not nil.
func (_u *EventUpdate) SetNillableAgentID(v *string) *EventUpdate {
	if v != nil {
		_u.SetAgentID(*v)
	}
	return _u
}

// SetChannelID sets the "channel_id" field.
func (_u *EventUpdate) SetChannelID(v string) *EventUpdate {
	_u.mutation.SetChannelID(v)
	return _u
}

// SetNillableChannelID sets the "channel_id" field if the given value is not nil.
func (_u *EventUpdate) SetNillableChannelID(v *string) *EventUpdate {
	if v != nil {
		_u.SetChannelID(*v)
	}
	return _u
}

// SetType sets the "type" field.
func (_u *EventUpdate) SetType(v event.Type) *EventUpdate {
	_u.mutation.SetType(v)
	return _u
}

// SetNillableType sets the "type" field if the given value is not nil.
func (_u *EventUpdate) SetNillableType(v *event.Type) *EventUpdate {
	if v != nil {
		_u.SetType(*v)
	}
	return _u
}

// SetRole sets the "role" field.
func (_u *EventUpdate) SetRole(v event.Role) *EventUpdate {
	_u.mutation.SetRole(v)
	return _u
}

// SetNillableRole sets the "role" field if the given value is not nil.
func (_u *EventUpdate) SetNillableRole(v *event.Role) *EventUpdate {
	if v != nil {
		_u.SetRole(*v)
	}
	return _u
}

// SetTimestamp sets the "timestamp" field.
func (_u *EventUpdate) SetTimestamp(v time.Time) *EventUpdate {
	_u.mutation.SetTimestamp(v)
	return _u
}

// SetNillableTimestamp sets the "timestamp" field if the given value is not nil.
func (_u *EventUpdate) SetNillableTimestamp(v *time.Time) *EventUpdate {
	if v != nil {
		_u.SetTimestamp(*v)
	}
	return _u
}

// SetPayload sets the "payload" field.
func (_u *EventUpdate) SetPayload(v map[string]interface{}) *EventUpdate {
	_u.mutation.SetPayload(v)
	return _u
}

// SetStatus sets the "status" field.
func (_u *EventUpdate) SetStatus(v event.Status) *EventUpdate {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *EventUpdate) SetNillableStatus(v *event.Status) *EventUpdate {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetSourceAgentID sets the "source_agent_id" field.
func (_u *EventUpdate) SetSourceAgentID(v string) *EventUpdate {
	_u.mutation.SetSourceAgentID(v)
	return _u
}

// SetNillableSourceAgentID sets the "source_agent_id" field if the given value is not nil.
func (_u *EventUpdate) SetNillableSourceAgentID(v *string) *EventUpdate {
	if v != nil {
		_u.SetSourceAgentID(*v)
	}
	return _u
}

// ClearSourceAgentID clears the value of the "source_agent_id" field.
func (_u *EventUpdate) ClearSourceAgentID() *EventUpdate {
	_u.mutation.ClearSourceAgentID()
	return _u
}

// Mutation returns the EventMutation object of the builder.
func (_u *EventUpdate) Mutation() *EventMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *EventUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *EventUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *EventUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *EventUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *EventUpdate) check() error {
	if v, ok := _u.mutation.GetType(); ok {
		if err := event.TypeValidator(v); err != nil {
			return &ValidationError{Name: "type", err: fmt.Errorf(`ent: validator failed for field "Event.type": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Role(); ok {
		if err := event.RoleValidator(v); err != nil {
			return &ValidationError{Name: "role", err: fmt.Errorf(`ent: validator failed for field "Event.role": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Status(); ok {
		if err := event.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "Event.status": %w`, err)}
		}
	}
	return nil
}

func (_u *EventUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(event.Table, event.Columns, sqlgraph.NewFieldSpec(event.FieldID, field.TypeString))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.TenantID(); ok {
		_spec.SetField(event.FieldTenantID, field.TypeString, value)
	}
	if value, ok := _u.mutation.AgentID(); ok {
		_spec.SetField(event.FieldAgentID, field.TypeString, value)
	}
	if value, ok := _u.mutation.ChannelID(); ok {
		_spec.SetField(event.FieldChannelID, field.TypeString, value)
	}
	if value, ok := _u.mutation.GetType(); ok {
		_spec.SetField(event.FieldType, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.Role(); ok {
		_spec.SetField(event.FieldRole, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.Timestamp(); ok {
		_spec.SetField(event.FieldTimestamp, field.TypeTime, value)
	}
	if value, ok := _u.mutation.Payload(); ok {
		_spec.SetField(event.FieldPayload, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(event.FieldStatus, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.SourceAgentID(); ok {
		_spec.SetField(event.FieldSourceAgentID, field.TypeString, value)
	}
	if _u.mutation.SourceAgentIDCleared() {
		_spec.ClearField(event.FieldSourceAgentID, field.TypeString)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{event.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// EventUpdateOne is the builder for updating a single Event entity.
type EventUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *EventMutation
}

// SetTenantID sets the "tenant_id" field.
func (_u *EventUpdateOne) SetTenantID(v string) *EventUpdateOne {
	_u.mutation.SetTenantID(v)
	return _u
}

// SetNillableTenantID sets the "tenant_id" field if the given value is not nil.
func (_u *EventUpdateOne) SetNillableTenantID(v *string) *EventUpdateOne {
	if v != nil {
		_u.SetTenantID(*v)
	}
	return _u
}

// SetAgentID sets the "agent_id" field.
func (_u *EventUpdateOne) SetAgentID(v string) *EventUpdateOne {
	_u.mutation.SetAgentID(v)
	return _u
}

// SetNillableAgentID sets the "agent_id" field if the given value is not nil.
func (_u *EventUpdateOne) SetNillableAgentID(v *string) *EventUpdateOne {
	if v != nil {
		_u.SetAgentID(*v)
	}
	return _u
}

// SetChannelID sets the "channel_id" field.
func (_u *EventUpdateOne) SetChannelID(v string) *EventUpdateOne {
	_u.mutation.SetChannelID(v)
	return _u
}

// SetNillableChannelID sets the "channel_id" field if the given value is not nil.
func (_u *EventUpdateOne) SetNillableChannelID(v *string) *EventUpdateOne {
	if v != nil {
		_u.SetChannelID(*v)
	}
	return _u
}

// SetType sets the "type" field.
func (_u *EventUpdateOne) SetType(v event.Type) *EventUpdateOne {
	_u.mutation.SetType(v)
	return _u
}

// SetNillableType sets the "type" field if the given value is not nil.
func (_u *EventUpdateOne) SetNillableType(v *event.Type) *EventUpdateOne {
	if v != nil {
		_u.SetType(*v)
	}
	return _u
}

// SetRole sets the "role" field.
func (_u *EventUpdateOne) SetRole(v event.Role) *EventUpdateOne {
	_u.mutation.SetRole(v)
	return _u
}

// SetNillableRole sets the "role" field if the given value is not nil.
func (_u *EventUpdateOne) SetNillableRole(v *event.Role) *EventUpdateOne {
	if v != nil {
		_u.SetRole(*v)
	}
	return _u
}

// SetTimestamp sets the "timestamp" field.
func (_u *EventUpdateOne) SetTimestamp(v time.Time) *EventUpdateOne {
	_u.mutation.SetTimestamp(v)
	return _u
}

// SetNillableTimestamp sets the "timestamp" field if the given value is not nil.
func (_u *EventUpdateOne) SetNillableTimestamp(v *time.Time) *EventUpdateOne {
	if v != nil {
		_u.SetTimestamp(*v)
	}
	return _u
}

// SetPayload sets the "payload" field.
func (_u *EventUpdateOne) SetPayload(v map[string]interface{}) *EventUpdateOne {
	_u.mutation.SetPayload(v)
	return _u
}

// SetStatus sets the "status" field.
func (_u *EventUpdateOne) SetStatus(v event.Status) *EventUpdateOne {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *EventUpdateOne) SetNillableStatus(v *event.Status) *EventUpdateOne {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetSourceAgentID sets the "source_agent_id" field.
func (_u *EventUpdateOne) SetSourceAgentID(v string) *EventUpdateOne {
	_u.mutation.SetSourceAgentID(v)
	return _u
}

// SetNillableSourceAgentID sets the "source_agent_id" field if the given value is not nil.
func (_u *EventUpdateOne) SetNillableSourceAgentID(v *string) *EventUpdateOne {
	if v != nil {
		_u.SetSourceAgentID(*v)
	}
	return _u
}

// ClearSourceAgentID clears the value of the "source_agent_id" field.
func (_u *EventUpdateOne) ClearSourceAgentID() *EventUpdateOne {
	_u.mutation.ClearSourceAgentID()
	return _u
}

// Mutation returns the EventMutation object of the builder.
func (_u *EventUpdateOne) Mutation() *EventMutation {
	return _u.mutation
}

// Where appends a list predicates to the EventUpdate builder.
func (_u *EventUpdateOne) Where(ps ...predicate.Event) *EventUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *EventUpdateOne) Select(field string, fields ...string) *EventUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated Event entity.
func (_u *EventUpdateOne) Save(ctx context.Context) (*Event, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *EventUpdateOne) SaveX(ctx context.Context) *Event {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *EventUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *EventUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *EventUpdateOne) check() error {
	if v, ok := _u.mutation.GetType(); ok {
		if err := event.TypeValidator(v); err != nil {
			return &ValidationError{Name: "type", err: fmt.Errorf(`ent: validator failed for field "Event.type": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Role(); ok {
		if err := event.RoleValidator(v); err != nil {
			return &ValidationError{Name: "role", err: fmt.Errorf(`ent: validator failed for field "Event.role": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Status(); ok {
		if err := event.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "Event.status": %w`, err)}
		}
	}
	return nil
}

func (_u *EventUpdateOne) sqlSave(ctx context.Context) (_node *Event, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(event.Table, event.Columns, sqlgraph.NewFieldSpec(event.FieldID, field.TypeString))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Event.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, event.FieldID)
		for _, f := range fields {
			if !event.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != event.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.TenantID(); ok {
		_spec.SetField(event.FieldTenantID, field.TypeString, value)
	}
	if value, ok := _u.mutation.AgentID(); ok {
		_spec.SetField(event.FieldAgentID, field.TypeString, value)
	}
	if value, ok := _u.mutation.ChannelID(); ok {
		_spec.SetField(event.FieldChannelID, field.TypeString, value)
	}
	if value, ok := _u.mutation.GetType(); ok {
		_spec.SetField(event.FieldType, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.Role(); ok {
		_spec.SetField(event.FieldRole, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.Timestamp(); ok {
		_spec.SetField(event.FieldTimestamp, field.TypeTime, value)
	}
	if value, ok := _u.mutation.Payload(); ok {
		_spec.SetField(event.FieldPayload, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(event.FieldStatus, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.SourceAgentID(); ok {
		_spec.SetField(event.FieldSourceAgentID, field.TypeString, value)
	}
	if _u.mutation.SourceAgentIDCleared() {
		_spec.ClearField(event.FieldSourceAgentID, field.TypeString)
	}
	_node = &Event{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{event.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
