// Code generated by ent, DO NOT EDIT.

package ent

import (
	"time"

	"github.com/plexusone/agentcomms/ent/agent"
	"github.com/plexusone/agentcomms/ent/event"
	"github.com/plexusone/agentcomms/ent/schema"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	agentFields := schema.Agent{}.Fields()
	_ = agentFields
	// agentDescTenantID is the schema descriptor for tenant_id field.
	agentDescTenantID := agentFields[1].Descriptor()
	// agent.DefaultTenantID holds the default value on creation for the tenant_id field.
	agent.DefaultTenantID = agentDescTenantID.Default.(string)
	eventFields := schema.Event{}.Fields()
	_ = eventFields
	// eventDescTenantID is the schema descriptor for tenant_id field.
	eventDescTenantID := eventFields[1].Descriptor()
	// event.DefaultTenantID holds the default value on creation for the tenant_id field.
	event.DefaultTenantID = eventDescTenantID.Default.(string)
	// eventDescTimestamp is the schema descriptor for timestamp field.
	eventDescTimestamp := eventFields[6].Descriptor()
	// event.DefaultTimestamp holds the default value on creation for the timestamp field.
	event.DefaultTimestamp = eventDescTimestamp.Default.(func() time.Time)
	// eventDescSourceAgentID is the schema descriptor for source_agent_id field.
	eventDescSourceAgentID := eventFields[9].Descriptor()
	// event.DefaultSourceAgentID holds the default value on creation for the source_agent_id field.
	event.DefaultSourceAgentID = eventDescSourceAgentID.Default.(string)
}
